- name: Cria diretórios de configuração
  hosts: localhost
  tasks:
    - name: Cria awesome config dir
      ansible.builtin.command: mkdir -p ~/.config/awesome/
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: '''successfully'' in command_result.stdout'
    - name: Cria docker config dir
      ansible.builtin.command: mkdir -p /etc/docker
      become: true
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: '''successfully'' in command_result.stdout'
- name: Cria estrutura de diretório de repositórios
  hosts: localhost
  tasks:
    - name: Repos github.com
      ansible.builtin.command: mkdir -p /data/repos/{{ item }}
      with_items: "{{ repos }}"
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: '''successfully'' in command_result.stdout'
- name: Arquivos de configuração
  hosts: localhost
  tasks:
    - name: Download gitconfig
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/edueo/config/main/gitconfig'
        dest: ~/.gitconfig
        mode: '644'
    - name: Download awesome config
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/edueo/config/main/rc.lua'
        dest: ~/.config/awesome/rc.lua
        mode: '644'
    - name: Download bashrc config
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/edueo/config/main/bashrc'
        dest: ~/.bashrc
        mode: '644'
- name: Instalação de pacotes
  hosts: localhost
  tasks:
    - name: Install browsers
      community.general.pacman:
        name: '{{ browsers }}'
        state: present
      become: true
      tags:
        - browsers
    - name: Install development tools
      community.general.pacman:
        name: '{{ development }}'
        state: present
      become: true
      tags:
        - development-tools
    - name: Install editors
      community.general.pacman:
        name: '{{ editors }}'
        state: present
      become: true
      tags:
        - editors
    - name: Install utilities
      community.general.pacman:
        name: '{{ utilities }}'
        state: present
      become: true
      tags:
        - utilities
    - name: Install cloud tools
      community.general.pacman:
        name: '{{ cloud_tools }}'
        state: present
      become: true
      tags:
        - cloud_tools
    - name: Install desktop environment
      community.general.pacman:
        name: '{{ desktop_environment }}'
        state: present
      become: true
      tags:
        - desktop_enviroment
    - name: Install LunarVim
      ansible.builtin.shell: >-
        LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s
        https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: '''successfully'' in command_result.stdout'
      tags:
        - lunarvim
    - name: Clone ASDF repo
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/asdf-vm.git'
        dest: ~/.asdf-vm
        single_branch: 'yes'
        version: master
      tags:
        - asdf
    - name: Install ASDF
      ansible.builtin.command: makepkg -si --noconfirm
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: '''successfully'' in command_result.stdout'
      args:
        chdir: ~/.asdf-vm/
      tags:
        - asdf
    - name: Docker daemon config
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/edueo/config/main/docker/daemon.json'
        dest: /etc/docker/daemon.json
        mode: '644'
      become: true
    - name: Enable docker service
      ansible.builtin.systemd:
        name: docker.service
        enabled: true
      become: true
    - name: Make sure a docker service unit is running
      ansible.builtin.systemd:
        state: started
        name: docker.service
      become: true
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: Adding eduardo to docker group
      ansible.builtin.user:
        name: eduardo
        groups: docker
        append: true
      become: true
    - name: Install ASDF plugins
      ansible.builtin.command: asdf plugin add {{ item }}
      with_items: "{{ asdf_plugins }}"
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: '''successfully'' in command_result.stdout'
      tags:
        - asdf
    - name: Download and extract maven
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
        dest: ~/
        remote_src: true
      tags:
        - apache-maven
    - name: Download and extract IntelliJ IDEA Community Edition
      ansible.builtin.unarchive:
        src: https://download.jetbrains.com/idea/ideaIC-2023.2.2.tar.gz
        dest: ~/
        remote_src: true
      tags:
        - jetbrains-intellij-idea
