- name: Cria diretórios de configuração
  hosts: localhost
  tasks:
    - name: Cria awesome config dir
      ansible.builtin.command: mkdir -p ~/.config/awesome/
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: '''successfully'' in command_result.stdout'

- name: Arquivos de configuração
  hosts: localhost
  tasks:
    - name: Download gitconfig
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/edueo/config/main/gitconfig'
        dest: ~/.gitconfig
        mode: '644'

    - name: Download awesome config
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/edueo/config/main/rc.lua'
        dest: ~/.config/awesome/rc.lua
        mode: '644'

- name: Instalação de pacotes
  hosts: localhost
  tasks:
    - name: Install browsers
      community.general.pacman:
        name: '{{ browsers }}'
        state: present
      become: true
      tags:
        - browsers
    - name: Install development tools
      community.general.pacman:
        name: '{{ development }}'
        state: present
      become: true
      tags:
        - development-tools
    - name: Install editors
      community.general.pacman:
        name: '{{ editors }}'
        state: present
      become: true
      tags:
        - editors
    - name: Install utilities
      community.general.pacman:
        name: '{{ utilities }}'
        state: present
      become: true
      tags:
        - utilities
    - name: Install cloud tools
      community.general.pacman:
        name: '{{ cloud_tools }}'
        state: present
      become: true
      tags:
        - cloud_tools
    - name: Install desktop environment
      community.general.pacman:
        name: '{{ desktop_environment }}'
        state: present
      become: true
      tags:
        - desktop_enviroment
    - name: Install LunarVim
      ansible.builtin.shell: >-
        LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s
        https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)
      register: command_result
      failed_when: command_result.rc != 0
      changed_when: '''successfully'' in command_result.stdout'
      tags:
        - lunarvim
    - name: Clone ASDF repo
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/asdf-vm.git'
        dest: ~/asdf-vm
        single_branch: 'yes'
        version: master
      tags:
        - asdf
