---

- name: Install Visual Studio Code
  ansible.builtin.command: yay -Syy visual-studio-code-bin --noconfirm
  register: command_result
  failed_when: command_result.rc != 0
  changed_when: '''successfully'' in command_result.stdout'
  tags:
    - visual-studio-code-bin
  become: false
  become_user: "{{ local_username }}"


- name: Install some popular vscode extensions
  ansible.builtin.command: code --install-extension {{ item }}
  with_items: "{{ code_extensions }}"
  become: false
  become_user: "{{ local_username }}"
