---

- block:
  
  - name: Get Manjaro version 
    ansible.builtin.shell: uname -r 
    register: command_result

  - name: search virtualbox pacman package
    ansible.builtin.shell: pacman -Ss virtualbox-host-modules | grep linux{{command_result.stdout[0:3] | replace('.', '') }}-virtualbox-host-modules 
    register: result 
    failed_when: command_result.rc != 0
    changed_when: '''successfully'' in command_result.stdout'
    become: True
    become_user: "{{local_username}}"
  
  - name: Install virtualbox-host-modules
    community.general.pacman:
     name: linux{{command_result.stdout[0:3] | replace('.', '') }}-virtualbox-host-modules
     state: present
  
  - name: Install virtualbox
    community.general.pacman:
     name: virtualbox
     state: present
  
  - name: Install virtualbox-guest-utils
    community.general.pacman:
     name: virtualbox-guest-utils
     state: present
  
  - name: Reload virtualbox virtualbox modules 
    ansible.builtin.shell: vboxreload
    become: True
    become_user: "{{ local_username }}"

    
  - name: Adiciona usuário no grupo do virtualbox 
    ansible.builtin.shell: usermod -aG vboxusers $USER
    become: True
    become_user: "{{ local_username }}"

