---
- name: Run the equivalent of "pacman -Su" as a separate step
  community.general.pacman:
    upgrade: true

- name: Install base base developer tools
  community.general.pacman:
    name: '{{ base_developer_tools }}'
    state: present

- name: Install base utilities
  community.general.pacman:
    name: '{{ base_utilities }}'
    state: present



